project:
  type: book
  output-dir: _book

book:
  title: "Manual de Mapeamento de Fogo: uma aplicação na gestão de áreas protegidas no cerrado maranhense"
  reader-mode: true
  

  cover-image: cover.png
  favicon: cover.png
  #site-url: https://r4ds.hadley.nz/
  repo-url: https://github.com/IzadoraSC/Manual-GeMFogo.github.io/
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    
    #- preface.qmd
    - intro.qmd
    # - part: Ferramentas
    #   chapters: 
    - cap1.qmd
    - cap2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - r4ds.scss
    css: styles.css
    code-link: true
    author-meta: "Izadora S. de Carvalho, Swanni T. Alvarado, Tiago Massi Ferraz"
    callout-appearance: simple
    


editor: visual
